/**
 * Copies the codicon glyphs the webview uses out of @vscode/codicons and into
 * src/webview/lib/icons.ts, so the webview ships real VS Code geometry without
 * loading a font or taking a runtime dependency.
 *
 * Run with: npm run icons
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const spritePath = require.resolve('@vscode/codicons/dist/codicon.svg');

/** Codicon id -> the name the webview uses. */
const WANTED = {
  'chevron-right': 'chevron-right',
  'git-branch': 'git-branch',
  'circle-filled': 'circle-filled',
  'circle-large-outline': 'circle-outline',
  'tag': 'tag',
  'archive': 'archive',
  'folder': 'folder',
  'root-folder': 'root-folder',
  'file-submodule': 'file-submodule',
  'layout-sidebar-left': 'layout-sidebar-left',
  'layout-sidebar-right': 'layout-sidebar-right',
  'refresh': 'refresh',
  'close': 'close',
  'repo': 'repo',
  'filter': 'filter',
};

const sprite = readFileSync(spritePath, 'utf8');

function extract(id) {
  const symbol = sprite.match(new RegExp(`<symbol[^>]*\\bid="${id}"[^>]*>([\\s\\S]*?)</symbol>`));
  if (!symbol) throw new Error(`codicon "${id}" not found in ${spritePath}`);

  const viewBox = sprite.match(new RegExp(`<symbol[^>]*\\bid="${id}"[^>]*viewBox="([^"]+)"`))?.[1]
    ?? sprite.match(new RegExp(`<symbol[^>]*viewBox="([^"]+)"[^>]*\\bid="${id}"`))?.[1];
  if (viewBox !== '0 0 16 16') throw new Error(`codicon "${id}" has an unexpected viewBox: ${viewBox}`);

  const paths = [...symbol[1].matchAll(/<path[^>]*\bd="([^"]+)"/g)].map(match => match[1]);
  if (paths.length !== 1) throw new Error(`codicon "${id}" has ${paths.length} paths; expected exactly 1`);
  return paths[0];
}

const entries = Object.entries(WANTED)
  .map(([id, name]) => `  '${name}': '${extract(id).replace(/'/g, "\\'")}',`)
  .join('\n');

const source = `// GENERATED by scripts/extract-icons.mjs from @vscode/codicons. Do not edit by hand.
// Run \`npm run icons\` to refresh after changing the wanted-icon list.

/** Codicon outlines on a 16x16 grid, inlined so the webview needs no icon font. */
export const iconPaths = {
${entries}
} as const;

export type IconName = keyof typeof iconPaths;

export const iconNames = Object.keys(iconPaths) as IconName[];
`;

writeFileSync(new URL('../src/webview/lib/icons.ts', import.meta.url), source);
console.log(`Wrote ${Object.keys(WANTED).length} icons to src/webview/lib/icons.ts`);
